(clear)
(load "/home/anton/Dropbox/sudoku_solver/s_main.erl")
(load "/home/anton/Dropbox/sudoku_solver/s_solver.erl")
(load "/home/anton/Dropbox/sudoku_solver/s_printer.erl")
(load "/home/anton/Dropbox/sudoku_solver/s_sudoku.erl")
(reset)
